name: Test, lint and build

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test_lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install packages
        run: yarn

      - name: Run Formatting Checks
        run: lerna run format

      - name: Run Linters
        run: lerna run lint

      - name: Run Build
        run: lerna run build

      - name: Run Tests
        run: lerna run test
